project_id = "rojwxgndtunssjdwngrh"

[functions.platform-provision-admin]
verify_jwt = true

[functions.erp-chat]
verify_jwt = false

[functions.erp-insights]
verify_jwt = false

[functions.send-notification]
verify_jwt = false
