import { useEffect, useMemo, useState } from 'react';
import { Calculator, CheckCircle2, PackageCheck, Plus, RefreshCw, Save, Ship, Trash2 } from 'lucide-react';
import { supabase } from '../../integrations/supabase/client';
import { calculateLandedCost } from './landedCost.js';
import { getCostingLines, listShipments, recalculateShipment, receiveShipment, removeShipmentCost, removeShipmentLine, saveShipment, saveShipmentCost, saveShipmentLine, updateShipmentWarehouse } from './landedCostService.js';
const today=()=>new Date().toISOString().slice(0,10); const money=n=>`${Number(n||0).toFixed(2)} ₼`;
const costTypes={customs_duty:'Gömrük rüsumu',customs_clearance:'Gömrük rəsmiləşdirilməsi',broker:'Broker xidməti',international_freight:'Beynəlxalq nəqliyyat',local_freight:'Yerli nəqliyyat',terminal:'Terminal',insurance:'Sığorta',certification:'Sertifikatlaşdırma',other:'Digər'};
const methods={invoice_value:'Invoice dəyərinə görə',volume:'Həcmə görə',weight:'Çəkiyə görə',quantity:'Miqdara görə',equal:'Bərabər',direct:'Məhsula birbaşa',manual:'Əl ilə'};
const statusLabels={draft:'Qaralama',in_transit:'Yoldadır',arrived:'Çatıb',costing:'Maya hesablanır',costed:'Maya təsdiqlənib',received:'Tamamlandı',closed:'Bağlanıb',cancelled:'Ləğv edilib'};
export default function LandedCostPanel({tenantId}){
 const [shipments,setShipments]=useState([]),[poLines,setPoLines]=useState([]),[warehouses,setWarehouses]=useState([]),[selected,setSelected]=useState(null),[costing,setCosting]=useState([]),[message,setMessage]=useState('');
 const [header,setHeader]=useState({shipment_no:`SHP-${Date.now()}`,container_no:'',shipment_date:today(),expected_arrival_date:'',origin_country:'',destination_country:'Azərbaycan',transport_mode:'Dəniz',carrier:'',currency:'AZN',status:'draft',notes:''});
 const [line,setLine]=useState({po_line_id:'',shipped_qty:1,received_qty:1,lot_no:''});
 const [cost,setCost]=useState({cost_type:'international_freight',amount:'',currency:'AZN',exchange_rate:1,allocation_method:'volume',document_no:'',cost_date:today(),notes:''});
 const load=async selectedId=>{try{const keepId=selectedId||selected?.id;const [s,p,w]=await Promise.all([listShipments(tenantId),supabase.from('purchase_order_lines').select('*, po:purchase_orders(id,po_number,currency,exchange_rate,status)').order('created_at',{ascending:false}),supabase.from('warehouses').select('*').eq('tenant_id',tenantId).eq('is_active',true)]);setShipments(s||[]);setPoLines(p.data||[]);setWarehouses(w.data||[]);if(keepId){const next=(s||[]).find(x=>x.id===keepId);setSelected(next||null);}}catch(e){setMessage(e.message)}};
 useEffect(()=>{load()},[tenantId]);
 const shippedByPo=useMemo(()=>{const totals=new Map();shipments.flatMap(s=>s.lines||[]).forEach(item=>totals.set(item.po_line_id,(totals.get(item.po_line_id)||0)+Number(item.shipped_qty||0)));return totals},[shipments]);
 const availablePoLines=useMemo(()=>poLines.filter(item=>Number(item.qty_ordered)-Number(shippedByPo.get(item.id)||0)>0.000001),[poLines,shippedByPo]);
 const selectedPoLine=poLines.find(item=>item.id===line.po_line_id);
 const selectedRemaining=selectedPoLine?Math.max(0,Number(selectedPoLine.qty_ordered)-Number(shippedByPo.get(selectedPoLine.id)||0)):0;
 const preview=useMemo(()=>{if(!selected?.lines?.length)return[];try{return calculateLandedCost(selected.lines.map(x=>({id:x.id,invoiceAmount:Number(x.invoice_amount_base),volume:Number(x.total_volume_m3),weight:Number(x.total_weight_kg),quantity:Number(x.shipped_qty),receivedQty:Number(x.received_qty),dutyRate:Number(x.duty_rate)})),(selected.costs||[]).map(x=>({id:x.id,type:x.cost_type,amount:Number(x.amount_base),method:x.allocation_method,lineId:x.direct_shipment_line_id})));}catch(e){return [{error:e.message}] }},[selected]);
 const create=async()=>{try{const shipmentNo=`SHP-${Date.now()}`;const s=await saveShipment({...header,shipment_no:shipmentNo,status:'draft',tenant_id:tenantId,created_by:(await supabase.auth.getUser()).data.user?.id});setHeader(current=>({...current,shipment_no:`SHP-${Date.now()+1}`,container_no:'',notes:''}));await load(s.id);setMessage(`${shipmentNo} yaradıldı. İndi aktiv PO-dan məhsul əlavə edin.`)}catch(e){setMessage(e.message)}};
 const addLine=async()=>{const p=poLines.find(x=>x.id===line.po_line_id);if(!p||!selected)return;const already=Number(shippedByPo.get(p.id)||0),amount=Number(line.shipped_qty),remaining=Math.max(0,Number(p.qty_ordered)-already);if(!Number.isFinite(amount)||amount<=0){setMessage('Göndərilən miqdar sıfırdan böyük olmalıdır.');return}if(amount>remaining+0.000001){setMessage(`Sifariş qalığı keçilir. Maksimum ${remaining}.`);return}try{await saveShipmentLine({...line,shipped_qty:amount,received_qty:Math.min(amount,Number(line.received_qty||amount)),tenant_id:tenantId,shipment_id:selected.id,invoice_unit_price:p.unit_price,exchange_rate:p.po?.exchange_rate||1,total_volume_m3:amount*Number(p.unit_volume_m3||0),total_weight_kg:amount*Number(p.unit_gross_weight_kg||0),duty_rate:p.duty_rate||0});setLine({po_line_id:'',shipped_qty:1,received_qty:1,lot_no:''});await load();}catch(e){setMessage(e.message)}};
 const addCost=async()=>{if(!selected)return;try{let extra={};if(cost.allocation_method==='direct'){const id=window.prompt('Birbaşa xərc üçün göndəriş sətri ID-si:',selected.lines?.[0]?.id||'');if(!id)return;extra.direct_shipment_line_id=id;}if(cost.allocation_method==='manual'){const manual={};for(const item of selected.lines||[]){const label=poLines.find(p=>p.id===item.po_line_id)?.description||item.id;const value=window.prompt(`${label} üçün bölüşdürülən məbləğ:`,'0');if(value===null)return;manual[item.id]=Number(value||0);}extra.manual_allocations=manual;}await saveShipmentCost({...cost,...extra,tenant_id:tenantId,shipment_id:selected.id,amount:Number(cost.amount),exchange_rate:Number(cost.exchange_rate)});await load();}catch(e){setMessage(e.message)}};
 const calculate=async approve=>{try{const version=await recalculateShipment(selected.id,approve);setCosting(await getCostingLines(selected.id,version));await load();setMessage(approve?'Maya təsdiqləndi.':'Hesablama yeniləndi.')}catch(e){setMessage(e.message)}};
 const chooseWarehouse=async warehouseId=>{try{const updated=await updateShipmentWarehouse(selected.id,tenantId,warehouseId);setSelected({...selected,warehouse_id:updated.warehouse_id});setShipments(items=>items.map(item=>item.id===selected.id?{...item,warehouse_id:updated.warehouse_id}:item));setMessage('')}catch(e){setMessage(e.message)}};
 const receive=async()=>{try{if(!selected.warehouse_id)throw new Error('Qəbul ediləcək anbarı seçin.');await receiveShipment(selected.id,selected.warehouse_id,today());await load();setMessage('Məhsullar yekun maya ilə anbara qəbul edildi.')}catch(e){setMessage(e.message)}};
 const completed=selected&&['received','closed'].includes(selected.status);
 return <div className="landed-cost-workspace">
  {message&&<div className="landed-message">{message}<button onClick={()=>setMessage('')}>×</button></div>}
  <div className="landed-toolbar"><span className="landed-toolbar-hint">Hər ayrıca mədaxil üçün yeni SHP yaradın; bir SHP-yə bir və ya bir neçə PO əlavə edilə bilər.</span><button className="primary-btn" onClick={create}><Plus size={15}/>Yeni SHP yarat</button><button className="secondary-btn" onClick={()=>load()}><RefreshCw size={15}/>Yenilə</button></div>
  <div className="landed-layout"><aside className="landed-list">{shipments.map(s=><button className={`${selected?.id===s.id?'active ':''}${['received','closed'].includes(s.status)?'completed':''}`} onClick={()=>setSelected(s)} key={s.id}><span className="landed-list-title"><strong>{s.shipment_no}</strong>{['received','closed'].includes(s.status)&&<CheckCircle2 size={15}/>}</span><small>{s.container_no||'Konteyner yoxdur'} · {(s.lines||[]).length} məhsul</small><em>{statusLabels[s.status]||s.status}</em></button>)}</aside>
  <main className="landed-main">{!selected?<section className="landed-card"><h3>Yeni göndəriş/konteyner</h3><div className="landed-grid">{[['shipment_no','Göndəriş №'],['container_no','Konteyner №'],['shipment_date','Göndəriş tarixi','date'],['expected_arrival_date','Gözlənilən tarix','date'],['origin_country','Çıxış ölkəsi'],['destination_country','Təyinat ölkəsi'],['carrier','Daşıyıcı']].map(([k,l,t])=><label key={k}>{l}<input type={t||'text'} value={header[k]} onChange={e=>setHeader({...header,[k]:e.target.value})}/></label>)}</div></section>:<>
   <section className={`landed-card landed-shipment-head ${completed?'is-complete':''}`}><div className="landed-shipment-heading"><h3><Ship size={18}/>{selected.shipment_no} · {selected.container_no||'Konteyner'}</h3><span className="landed-status-badge">{completed&&<CheckCircle2 size={15}/>} {statusLabels[selected.status]||selected.status}</span></div>{completed?<div className="landed-complete-summary"><div><span>Qəbul anbarı</span><strong>{warehouses.find(x=>x.id===selected.warehouse_id)?.name||'Anbar'}</strong></div><div><span>Məhsul sayı</span><strong>{(selected.lines||[]).length}</strong></div><div><span>Qəbul vəziyyəti</span><strong>Tamamlanıb</strong></div></div>:<div className="landed-actions"><label className="landed-warehouse-picker"><span>Qəbul anbarı</span><select value={selected.warehouse_id||''} onChange={e=>chooseWarehouse(e.target.value)}><option value="">Anbar seçin</option>{warehouses.map(warehouse=><option key={warehouse.id} value={warehouse.id}>{warehouse.name}{warehouse.code?` (${warehouse.code})`:''}</option>)}</select></label><button onClick={()=>calculate(false)}><Calculator size={15}/>Yenidən hesabla</button><button onClick={()=>calculate(true)}><Save size={15}/>Mayanı təsdiqlə</button><button onClick={receive} disabled={selected.status!=='costed'||!selected.warehouse_id} title={!selected.warehouse_id?'Əvvəlcə qəbul anbarını seçin':''}><PackageCheck size={15}/>Anbara qəbul et</button></div>}{!completed&&warehouses.length===0&&<p className="landed-error">Aktiv anbar tapılmadı. Əvvəlcə Anbar modulunda anbar yaradın.</p>}</section>
   <section className="landed-card"><h3>{completed?'Qəbul edilmiş məhsullar':'Göndəriş sətirləri'}</h3>{!completed&&<div className="landed-inline"><select value={line.po_line_id} onChange={e=>{const p=poLines.find(item=>item.id===e.target.value);const remaining=p?Math.max(0,Number(p.qty_ordered)-Number(shippedByPo.get(p.id)||0)):1;setLine({...line,po_line_id:e.target.value,shipped_qty:remaining,received_qty:remaining})}}><option value="">PO məhsulu seçin</option>{availablePoLines.map(p=><option key={p.id} value={p.id}>{p.po?.po_number} · {p.description||p.product_sku} · qalıq {Number(p.qty_ordered)-Number(shippedByPo.get(p.id)||0)}</option>)}</select><input type="number" min=".001" max={selectedRemaining||undefined} step=".001" value={line.shipped_qty} onChange={e=>{const raw=e.target.value;if(raw===''){setLine({...line,shipped_qty:'',received_qty:''});return}const amount=Math.min(Math.max(0,Number(raw)||0),selectedRemaining);setLine({...line,shipped_qty:amount,received_qty:amount})}}/><button onClick={addLine} disabled={!line.po_line_id||selectedRemaining<=0}>Əlavə et</button></div>}<table><thead><tr><th>PO</th><th>Məhsul</th><th>Göndərilən</th><th>Qəbul</th><th>Invoice</th><th>Həcm</th>{!completed&&<th/>}</tr></thead><tbody>{(selected.lines||[]).map(x=>{const p=poLines.find(p=>p.id===x.po_line_id);return <tr key={x.id}><td>{p?.po?.po_number||'—'}</td><td><strong>{p?.description||p?.product_sku||x.po_line_id}</strong></td><td>{x.shipped_qty}</td><td>{x.received_qty}</td><td>{money(x.invoice_amount_base)}</td><td>{x.total_volume_m3}</td>{!completed&&<td><button onClick={async()=>{await removeShipmentLine(x.id);load()}}><Trash2 size={14}/></button></td>}</tr>})}</tbody></table></section>
   <section className="landed-card"><h3>Əlavə xərclər</h3>{!completed&&<div className="landed-inline"><select value={cost.cost_type} onChange={e=>setCost({...cost,cost_type:e.target.value,allocation_method:e.target.value.includes('freight')?'volume':'invoice_value'})}>{Object.entries(costTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input type="number" placeholder="Məbləğ" value={cost.amount} onChange={e=>setCost({...cost,amount:e.target.value})}/><select value={cost.allocation_method} onChange={e=>setCost({...cost,allocation_method:e.target.value})}>{Object.entries(methods).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={addCost}>Əlavə et</button></div>}{(selected.costs||[]).map(x=><div className="landed-cost-row" key={x.id}><span>{costTypes[x.cost_type]}</span><strong>{money(x.amount_base)}</strong><small>{methods[x.allocation_method]}</small>{!completed&&<button onClick={async()=>{await removeShipmentCost(x.id);load()}}><Trash2 size={14}/></button>}</div>)}</section>
   <section className="landed-card"><h3>Maya dəyərinin hesablanması</h3>{preview[0]?.error?<p className="landed-error">{preview[0].error}</p>:<table><thead><tr><th>Məhsul</th><th>Invoice</th><th>Gömrük</th><th>Nəqliyyat</th><th>Digər</th><th>Yekun</th><th>Vahid maya</th></tr></thead><tbody>{preview.map(x=><tr key={x.id}><td>{poLines.find(p=>p.id===(selected.lines||[]).find(l=>l.id===x.id)?.po_line_id)?.description||x.id}</td><td>{money(x.invoiceAmount)}</td><td>{money(x.customs)}</td><td>{money(x.freight)}</td><td>{money(x.other)}</td><td>{money(x.landedTotal)}</td><td><strong>{money(x.unitLandedCost)}</strong></td></tr>)}</tbody></table>}</section>
  </>}</main></div></div>;
}
