import { CalendarClock, CircleAlert, FileText, UserCog } from "lucide-react";
import { DataTable, MetricCard, Panel, PanelHeader, StatusBadge, TwoLine } from "../components/ui.jsx";
import { formatPaymentDate, parsePaymentDate } from "../services/date.js";
import { money } from "../services/format.js";
import { total } from "../shared/utils/aggregate.js";
import { currentBusinessDate, currentBusinessYear } from "../shared/lib/appDomain.jsx";
export default function TaxPage({ taxRows, payrollTaxRows, invoiceSummary, accounting }) {
  const overdue = taxRows.filter((row) => row.status === "Gecikib");
  const soon = taxRows.filter((row) => row.status === "Bu gün" || row.status === "Yaxınlaşır");
  const paidTasks = taxRows.filter((row) => row.paymentTaskId || row.paymentStatus === "Ödəniş tapşırığı");
  const autoRows = taxRows.filter((row) => row.autoGenerated);
  const totalTaxAmount = taxRows.reduce((sum, row) => sum + Number(row.amount || 0), 0);
  const soonAmount = soon.reduce((sum, row) => sum + Number(row.amount || 0), 0);
  const overdueAmount = overdue.reduce((sum, row) => sum + Number(row.amount || 0), 0);
  const payrollLiability = payrollTaxRows.reduce(
    (sum, row) =>
      sum +
      Number(row.incomeTax || 0) +
      Number(row.employeeSocial || 0) +
      Number(row.employeeUnemployment || 0) +
      Number(row.employerSocial || 0) +
      Number(row.employerUnemployment || 0),
    0,
  );
  const employerCost = total(payrollTaxRows, "employerCost");

  return (
    <div className="stack">
      <section className="metric-grid four">
        <MetricCard label="Yaxın öhdəlik" value={soon.length} icon={CalendarClock} tone="warning" />
        <MetricCard label="Gecikən" value={overdue.length} icon={CircleAlert} tone={overdue.length ? "danger" : "success"} />
        <MetricCard label="ƏDV bazası" value={money(invoiceSummary.vat)} icon={FileText} tone="info" />
        <MetricCard label="Payroll vergi/DSMF" value={money(payrollLiability)} icon={UserCog} tone="primary" />
      </section>

      <Panel className="tax-control-panel" data-testid="tax-control-panel">
        <PanelHeader
          title="Vergi öhdəlik nəzarəti"
          subtitle="ƏDV, mənfəət və payroll öhdəlikləri maliyyə və faktura datalarından avtomatik hesablanır"
          icon={CalendarClock}
        />
        <div className="tax-control-grid">
          <div>
            <span>Toplam öhdəlik</span>
            <strong>{money(totalTaxAmount)}</strong>
            <small>{taxRows.length} nəzarət sətri</small>
          </div>
          <div>
            <span>Yaxın ödəniş</span>
            <strong>{money(soonAmount)}</strong>
            <small>{soon.length} sətir prioritetdir</small>
          </div>
          <div>
            <span>Gecikmiş risk</span>
            <strong>{money(overdueAmount)}</strong>
            <small>{overdue.length} gecikən öhdəlik</small>
          </div>
          <div>
            <span>Ödəniş tapşırığı</span>
            <strong>{paidTasks.length}</strong>
            <small>{autoRows.length} avtomatik hesablanıb</small>
          </div>
        </div>
      </Panel>

      <Panel className="tax-calendar-panel">
        <PanelHeader title={`${currentBusinessYear} vergi təqvimi`} subtitle={`Bugünkü nəzarət tarixi: ${formatPaymentDate(parsePaymentDate(currentBusinessDate))}`} icon={CalendarClock} />
        <DataTable
          columns={["Öhdəlik", "Dövr", "Son tarix", "Qalan gün", "Təxmini məbləğ", "Məsul", "Mənbə", "Status"]}
          rows={taxRows.map((row) => [
            <TwoLine title={row.title} subtitle={row.type} />,
            row.period,
            row.dueDate,
            row.daysLeft >= 0 ? `${row.daysLeft} gün` : `${Math.abs(row.daysLeft)} gün gecikib`,
            money(row.amount),
            row.owner,
            row.paymentTaskId ? <TwoLine title="Tapşırıq yaradılıb" subtitle={row.paymentTaskId} /> : row.source || "Manual",
            <StatusBadge status={row.status} />,
          ])}
        />
      </Panel>

      <section className="accounting-statement-grid">
        <Panel>
          <PanelHeader title="ƏDV icmalı" subtitle="Faktura modulundan gələn ƏDV hesabı" />
          <div className="statement-list">
            <TwoLine title="Satış ƏDV" subtitle={money(invoiceSummary.vat)} />
            <TwoLine title="ƏDV öhdəliyi" subtitle={money(accounting.vatPayable)} />
            <TwoLine title="E-qaimə sayı" subtitle={`${invoiceSummary.count} faktura`} />
          </div>
        </Panel>
        <Panel>
          <PanelHeader title="Əmək haqqı kalkulyatoru" subtitle={`${currentBusinessYear} vergi, DSMF və işəgötürən xərci`} />
          <div className="statement-list">
            <TwoLine title="İşəgötürən xərci" subtitle={money(employerCost)} />
            <TwoLine title="Tutulmalar" subtitle={money(payrollLiability)} />
            <TwoLine title="Əməkdaş sayı" subtitle={payrollTaxRows.length} />
          </div>
        </Panel>
      </section>

      <Panel>
        <PanelHeader title="Payroll vergi hesabı" subtitle="Gross, gəlir vergisi, sosial ödəniş və net əmək haqqı" />
        <DataTable
          columns={["Əməkdaş", "Şöbə", "Gross", "Gəlir vergisi", "İşçi DSMF/işsizlik", "Net", "İşəgötürən xərci"]}
          rows={payrollTaxRows.map((row) => [
            <strong>{row.employee}</strong>,
            row.department,
            money(row.gross),
            money(row.incomeTax),
            money(row.employeeSocial + row.employeeUnemployment),
            <strong>{money(row.net)}</strong>,
            money(row.employerCost),
          ])}
        />
      </Panel>
    </div>
  );
}