import {
  BarChart3, Bell, Boxes, Building2, CalendarClock, CreditCard, FileText,
  LayoutDashboard, MessageSquare, Package, Settings, ShieldCheck, ShoppingCart,
  Sparkles, TrendingUp, Truck, UserCog, Users, Wallet, Warehouse,
} from "lucide-react";

export const navIcons = {
  dashboard: LayoutDashboard,
  assistant: Sparkles,
  platform: Building2,
  crm: Users,
  "crm-deals": TrendingUp,
  "crm-activities": MessageSquare,
  "crm-tasks": ShieldCheck,
  sales: ShoppingCart,
  "sales-dashboard": BarChart3,
  "sales-quotes": FileText,
  "sales-shipments": Truck,
  warehouse: Warehouse,
  stock: Boxes,
  deliveries: Truck,
  finance: Wallet,
  cashbook: Wallet,
  "ar-invoices": FileText,
  invoices: FileText,
  accounting: BarChart3,
  tax: CalendarClock,
  credits: CreditCard,
  receivables: Wallet,
  vendors: Building2,
  procurement: ShoppingCart,
  projects: BarChart3,
  production: Package,
  hr: UserCog,
  kpi: TrendingUp,
  contracts: FileText,
  reports: BarChart3,
  support: MessageSquare,
  help: FileText,
  onboarding: ShieldCheck,
  messages: MessageSquare,
  notifications: Bell,
  api: ShieldCheck,
  settings: Settings,
  roles: ShieldCheck,
  "access-check": ShieldCheck,
  audit: ShieldCheck,
  periods: FileText,
  currencies: FileText,
  "financial-statements": FileText,
};
