import { BarChart3, Download, SlidersHorizontal, TrendingUp, Wallet } from "lucide-react";
import {
  DataTable,
  EmptyState,
  MetricCard,
  Panel,
  PanelHeader,
  ProgressRow,
  StatusBadge,
  TwoLine,
} from "../../components/ui.jsx";
import { money, percent } from "../../services/format.js";
import { total } from "../../shared/utils/aggregate.js";
import { buildProjectRoiSummary } from "../../shared/analytics/projects.js";

export function ProjectsPage({ projects, snapshot = null }) {
  const summary = buildProjectRoiSummary(projects);
  const budget = total(projects, "budget");
  const collected = total(projects, "collected");
  const collectionRate = summary.revenue > 0 ? (collected / summary.revenue) * 100 : 0;

  return (
    <div className="stack">
      <section className="metric-grid four">
        <MetricCard label="Layihə gəliri" value={money(summary.revenue)} icon={Wallet} tone="success" />
        <MetricCard label="Committed xərc" value={money(summary.committedCost)} trend={`Büdcə: ${money(budget)}`} icon={BarChart3} tone="warning" />
        <MetricCard label="Mənfəət" value={money(summary.profit)} trend={`Proqnoz: ${money(summary.projectedProfit)}`} icon={TrendingUp} tone={summary.profit >= 0 ? "success" : "danger"} />
        <MetricCard label="Orta ROI" value={percent(summary.avgRoi)} trend={`${summary.riskCount} risk`} icon={SlidersHorizontal} tone={summary.riskCount ? "warning" : "primary"} />
      </section>
      <section className="project-roi-control-grid" data-testid="project-roi-control-panel">
        <div>
          <span>Yığım faizi</span>
          <strong>{percent(collectionRate)}</strong>
          <small>{money(collected)} toplanıb</small>
        </div>
        <div>
          <span>Report status</span>
          <strong>{snapshot ? "Hazır" : "Gözləyir"}</strong>
          <small>{snapshot ? `${snapshot.period} · ${snapshot.projects?.length || 0} layihə` : "ROI export düyməsini işə salın"}</small>
        </div>
        <div>
          <span>Riskli layihələr</span>
          <strong>{summary.riskCount}</strong>
          <small>Büdcə, mənfəət və yığım siqnalları</small>
        </div>
      </section>
      <Panel className="project-roi-panel">
        <PanelHeader title="Layihə və kampaniya ROI" subtitle="Məhsul, xərc kateqoriyası və satış nəticələri əsasında hesablanır" icon={BarChart3} />
        <DataTable
          columns={["Layihə", "Sahib", "Büdcə", "Satış/Yığım", "Xərc", "Mənfəət", "ROI", "Status", "Növbəti addım", "Hesabat"]}
          rows={projects.map((project) => [
            <TwoLine title={project.name} subtitle={`${project.start} → ${project.end}`} />,
            project.owner,
            money(project.budget || project.investmentBase),
            <TwoLine title={money(project.revenue)} subtitle={`${project.orders} sifariş · ${percent(project.collectionRate)} yığım`} />,
            <TwoLine title={money(project.totalCost)} subtitle={`Committed: ${money(project.committedCost)}`} />,
            <TwoLine title={money(project.profit)} subtitle={`Proqnoz: ${money(project.projectedProfit)}`} />,
            <ProgressRow value={Math.max(0, Math.min(100, project.roi))} caption={percent(project.roi)} compact />,
            <StatusBadge status={project.status} />,
            project.nextAction,
            project.lastExportAt || snapshot ? (
              <TwoLine title={project.lastExportAt || snapshot.generatedAt} subtitle={`${project.exportCount || 1} export`} />
            ) : (
              <StatusBadge status={project.reportStatus} />
            ),
          ])}
        />
      </Panel>
      <section className="dashboard-grid">
        <Panel className="project-roi-breakdown-panel span-2">
          <PanelHeader title="Xərc və gəlir breakdown" subtitle="Məhsul maya dəyəri, təsdiqli xərc, gözləyən xərc və budget usage" icon={Wallet} />
          <DataTable
            columns={["Layihə", "Məhsul maya", "Təsdiqli xərc", "Gözləyən xərc", "Budget usage", "Order ID-lər"]}
            rows={projects.map((project) => [
              <TwoLine title={project.name} subtitle={project.autoGenerated ? "Avtomatik portfel" : project.id} />,
              money(project.productCost),
              money(project.approvedExpenseCost),
              money(project.pendingExpenseCost),
              project.budget ? <ProgressRow value={Math.max(0, Math.min(100, project.budgetUsage))} caption={percent(project.budgetUsage)} compact /> : "—",
              project.orderIds?.length ? project.orderIds.slice(0, 4).join(", ") : "—",
            ])}
          />
        </Panel>
        <Panel className="project-report-panel">
          <PanelHeader title="ROI hesabat axını" subtitle="Son export snapshot-u və idarəetmə nəticəsi" icon={Download} />
          {snapshot ? (
            <div className="project-report-card">
              <StatusBadge status={snapshot.summary?.riskCount ? "Nəzarət" : "Hazır"} />
              <TwoLine title={snapshot.generatedAt} subtitle={`${snapshot.period} dövrü`} />
              <div>
                <span>Gəlir</span>
                <strong>{money(snapshot.summary?.revenue || 0)}</strong>
              </div>
              <div>
                <span>ROI</span>
                <strong>{percent(snapshot.summary?.avgRoi || 0)}</strong>
              </div>
              <div>
                <span>Risk</span>
                <strong>{snapshot.summary?.riskCount || 0}</strong>
              </div>
            </div>
          ) : (
            <EmptyState title="ROI hesabatı hələ export edilməyib" />
          )}
        </Panel>
      </section>
    </div>
  );
}
