export const stages = [
  "Zavod",
  "Anbardadır",
  "Yoldadır",
  "Hazırdır",
  "Təhvilə çıxıb",
  "Təhvil verilib",
];

export const navItems = [
  { id: "dashboard", label: "Panel" },
  { id: "assistant", label: "AI Köməkçi" },
  { id: "insights", label: "AI Tövsiyələr" },

  // CRM
  { id: "crm", label: "Müştərilər", group: "crm" },
  { id: "crm-deals", label: "Sövdələşmələr", group: "crm" },
  { id: "crm-activities", label: "Aktivliklər", group: "crm" },
  { id: "crm-tasks", label: "Tapşırıqlar", group: "crm" },

  // Satış
  { id: "sales-dashboard", label: "Satış paneli", group: "sales" },
  { id: "sales", label: "Satış yarat", group: "sales" },

  // Təchizat & Anbar
  { id: "procurement", label: "Satınalma", group: "supply" },
  { id: "stock", label: "Anbar idarəetməsi", group: "supply" },
  { id: "products", label: "Məhsullar", group: "supply" },
  { id: "deliveries", label: "Təhvil-təslim", group: "supply" },

  // Maliyyə
  { id: "cashbook", label: "Kassa & Xərclər", group: "finance" },
  { id: "ar-invoices", label: "Satış fakturaları", group: "finance" },
  { id: "accounting", label: "Mühasibat jurnalı", group: "finance" },
  { id: "receivables", label: "Borclar", group: "finance" },
  { id: "credits", label: "Kreditlər", group: "finance" },


  // Əməliyyat
  { id: "contracts", label: "Müqavilələr", group: "ops" },
  { id: "hr", label: "HR", group: "ops" },

  // Analitika
  { id: "reports", label: "Hesabatlar", group: "analytics" },
  { id: "financial-statements", label: "Maliyyə hesabatları", group: "analytics" },
  { id: "kpi", label: "KPI", group: "analytics" },
  { id: "bonuses", label: "Satıcı bonusları", group: "analytics" },

  // Sistem
  { id: "platform", label: "Şirkətlər", group: "system" },
  { id: "settings", label: "Ayarlar", group: "system" },
  { id: "roles", label: "İstifadəçilər", group: "system" },
  { id: "access-check", label: "İcazə yoxlaması", group: "system" },
  { id: "audit", label: "Audit izi", group: "system" },
  { id: "data-reconciliation", label: "Data barışdırması", group: "system" },

  { id: "api", label: "API & inteqrasiya", group: "system" },
  { id: "messages", label: "Mesajlar", group: "system" },
  { id: "notifications", label: "Bildirişlər", group: "system" },
  { id: "onboarding", label: "Onboarding", group: "system" },
  { id: "help", label: "Kömək", group: "system" },
  { id: "support", label: "Dəstək", group: "system" },
];



export const initialState = {
  customers: [],
  products: [],
  orders: [],
  stock: [],
  warehouses: [],
  warehouseStock: {},
  expenses: [],
  cashEntries: [],
  financeAccounts: [],
  credits: [],
  vendors: [],
  employees: [],
  departments: [],
  leaveRequests: [],
  vacancies: [],
  contracts: [],
  kpiTargets: [
    {
      id: "KPI-TGT-COMPANY",
      name: "Şirkət orta KPI",
      metricKey: "companyKpi",
      target: 95,
      unit: "%",
      weight: 30,
      owner: "HR",
      status: "Aktiv",
    },
    {
      id: "KPI-TGT-SALES-BONUS",
      name: "Satış bonus fondu",
      metricKey: "salesBonus",
      target: 3000,
      unit: "AZN",
      weight: 35,
      owner: "Satış",
      status: "Aktiv",
    },
    {
      id: "KPI-TGT-HR-BONUS",
      name: "Performans bonus fondu",
      metricKey: "hrBonus",
      target: 2500,
      unit: "AZN",
      weight: 20,
      owner: "HR/Maliyyə",
      status: "Aktiv",
    },
    {
      id: "KPI-TGT-TEAM",
      name: "95%+ KPI əməkdaş payı",
      metricKey: "highPerformers",
      target: 70,
      unit: "%",
      weight: 15,
      owner: "Rəhbərlik",
      status: "Aktiv",
    },
  ],
  kpiPeriods: [],
  kpiPayouts: [],
  notifications: [],
  conversations: [],
  notificationRules: [
    {
      id: "RULE-CREDIT-OVERDUE",
      name: "Kredit ödəniş xatırlatması",
      channel: "SMS",
      providerId: "PROV-SMS",
      trigger: "Kredit ödənişi bu gün və ya gecikib",
      template: "{customer}, {contractId} üzrə ödənişiniz {amount} AZN-dir.",
      owner: "Kredit şöbəsi",
      status: "Aktiv",
      cooldownHours: 24,
    },
    {
      id: "RULE-CREDIT-UPCOMING",
      name: "Yaxınlaşan kredit ödənişi",
      channel: "SMS",
      providerId: "PROV-SMS",
      trigger: "Kredit ödənişinə 1-3 gün qalıb",
      template: "{customer}, {contractId} üzrə {dueDate} tarixli ödənişiniz {amount} AZN-dir.",
      owner: "Kredit şöbəsi",
      status: "Aktiv",
      cooldownHours: 24,
    },
    {
      id: "RULE-LOW-STOCK",
      name: "Minimum stok xəbərdarlığı",
      channel: "Push",
      providerId: "PROV-PUSH",
      trigger: "Mövcud stok minimum həddən aşağıdır",
      template: "{product} üzrə stok {available} ədədə düşüb.",
      owner: "Anbar",
      status: "Aktiv",
      cooldownHours: 12,
    },
    {
      id: "RULE-PO-APPROVAL",
      name: "PO təsdiq xatırlatması",
      channel: "Email",
      providerId: "PROV-EMAIL",
      trigger: "Satınalma sifarişi təsdiq gözləyir",
      template: "{poId} təsdiq gözləyir. Məbləğ: {amount} AZN.",
      owner: "Satınalma",
      status: "Aktiv",
      cooldownHours: 24,
    },
    {
      id: "RULE-PAYROLL",
      name: "Payroll təsdiq siqnalı",
      channel: "Email",
      providerId: "PROV-EMAIL",
      trigger: "HR payroll xərci təsdiq gözləyir",
      template: "Payroll xərci təsdiq üçün hazırdır: {amount} AZN.",
      owner: "HR/Maliyyə",
      status: "Aktiv",
      cooldownHours: 24,
    },
    {
      id: "RULE-DELIVERY-SLA",
      name: "Təhvil SLA xatırlatması",
      channel: "Push",
      providerId: "PROV-PUSH",
      trigger: "Təhvil sifarişi 5+ gün açıqdır",
      template: "{orderId} təhvil SLA riski daşıyır.",
      owner: "Anbar/Təhvil",
      status: "Aktiv",
      cooldownHours: 8,
    },
  ],
  notificationProviders: [
    {
      id: "PROV-SMS",
      channel: "SMS",
      name: "SMS Gateway",
      provider: "Local/Sandbox",
      endpoint: "https://sms.provider.local/send",
      sender: "ERPCRM",
      status: "Aktiv",
      mode: "Sandbox",
      secretStatus: "Secret tələb olunur",
    },
    {
      id: "PROV-EMAIL",
      channel: "Email",
      name: "SMTP Email",
      provider: "SMTP",
      endpoint: "smtp://mail.provider.local",
      sender: "no-reply@erp.local",
      status: "Aktiv",
      mode: "Sandbox",
      secretStatus: "Secret tələb olunur",
    },
    {
      id: "PROV-PUSH",
      channel: "Push",
      name: "Web Push",
      provider: "VAPID",
      endpoint: "/push/send",
      sender: "ERP Web",
      status: "Aktiv",
      mode: "Sandbox",
      secretStatus: "Secret tələb olunur",
    },
  ],
  notificationSendLog: [],
  notificationDispatchSnapshot: null,
  projects: [],
  productionPlans: [],
  supportTickets: [],
  knowledgeBase: [],
  taxCalendar: [],
  currencyRates: [],
  apiWebhooks: [
    {
      id: "WH-CREDIT-OVERDUE",
      name: "Gecikən kredit xatırlatma",
      event: "credit.overdue",
      method: "POST",
      target: "https://integrations.erp.local/webhooks/credit-overdue",
      authType: "HMAC",
      secretKey: "ERP_WEBHOOK_SIGNING_SECRET",
      owner: "Kredit şöbəsi",
      status: "Aktiv",
      slaSeconds: 30,
      retryMax: 3,
      retryBackoffSeconds: 60,
      processedCount: 0,
      failureCount: 0,
      retryQueue: 0,
    },
    {
      id: "WH-LOW-STOCK",
      name: "Minimum stok xəbərdarlığı",
      event: "product.low_stock",
      method: "POST",
      target: "https://integrations.erp.local/webhooks/low-stock",
      authType: "Bearer token",
      secretKey: "WAREHOUSE_API_TOKEN",
      owner: "Anbar",
      status: "Aktiv",
      slaSeconds: 45,
      retryMax: 5,
      retryBackoffSeconds: 120,
      processedCount: 0,
      failureCount: 0,
      retryQueue: 0,
    },
    {
      id: "WH-INVOICE-PAID",
      name: "Faktura ödənişi",
      event: "invoice.paid",
      method: "POST",
      target: "https://integrations.erp.local/webhooks/invoice-paid",
      authType: "HMAC",
      secretKey: "ERP_WEBHOOK_SIGNING_SECRET",
      owner: "Maliyyə",
      status: "Aktiv",
      slaSeconds: 30,
      retryMax: 3,
      retryBackoffSeconds: 90,
      processedCount: 0,
      failureCount: 0,
      retryQueue: 0,
    },
    {
      id: "WH-PO-APPROVED",
      name: "PO təsdiq edildi",
      event: "po.approved",
      method: "POST",
      target: "https://vendor-gateway.erp.local/webhooks/po-approved",
      authType: "Bearer token",
      secretKey: "VENDOR_GATEWAY_TOKEN",
      owner: "Satınalma",
      status: "Aktiv",
      slaSeconds: 60,
      retryMax: 5,
      retryBackoffSeconds: 180,
      processedCount: 0,
      failureCount: 0,
      retryQueue: 0,
    },
    {
      id: "WH-PAYROLL-CREATED",
      name: "Payroll yaradıldı",
      event: "payroll.created",
      method: "POST",
      target: "https://finance.erp.local/webhooks/payroll-created",
      authType: "HMAC",
      secretKey: "ERP_WEBHOOK_SIGNING_SECRET",
      owner: "HR/Maliyyə",
      status: "Test",
      slaSeconds: 90,
      retryMax: 2,
      retryBackoffSeconds: 300,
      processedCount: 0,
      failureCount: 0,
      retryQueue: 0,
    },
  ],
  apiSecrets: [
    {
      id: "SEC-WEBHOOK-SIGNING",
      key: "ERP_WEBHOOK_SIGNING_SECRET",
      label: "ERP webhook imza açarı",
      type: "HMAC secret",
      maskedValue: "whsec_••••••••42A9",
      status: "Aktiv",
      owner: "Platform",
      scope: "Bütün ERP outbound webhook-ları",
      rotationDays: 90,
      lastRotatedAt: "2026-07-01",
      version: 1,
    },
    {
      id: "SEC-WAREHOUSE-TOKEN",
      key: "WAREHOUSE_API_TOKEN",
      label: "Anbar inteqrasiya tokeni",
      type: "Bearer token",
      maskedValue: "wms_••••••••19F2",
      status: "Aktiv",
      owner: "Anbar",
      scope: "WMS / stok webhook-ları",
      rotationDays: 60,
      lastRotatedAt: "2026-07-01",
      version: 1,
    },
    {
      id: "SEC-VENDOR-TOKEN",
      key: "VENDOR_GATEWAY_TOKEN",
      label: "Vendor gateway tokeni",
      type: "Bearer token",
      maskedValue: "vnd_••••••••77BC",
      status: "Aktiv",
      owner: "Satınalma",
      scope: "Vendor PO endpoint-ləri",
      rotationDays: 60,
      lastRotatedAt: "2026-07-01",
      version: 1,
    },
  ],
  apiWebhookLogs: [],
  apiIntegrationSnapshot: null,
  purchaseOrders: [],
  auditLog: [],
  reportExports: [],
  receivableClosures: [],
  projectRoiSnapshot: null,
  accountingClose: null,
  receivableSync: null,
  notificationSweepAt: null,
  integritySnapshot: null,
  goLiveSnapshot: null,
  productionHardeningSnapshot: null,
  helpGuideSnapshot: null,
  onboarding: {
    companyStage: "İlkin qurulum",
    businessArea: "",
    employeeCount: "",
    steps: [
      { id: "ONB-1", title: "Şirkət məlumatlarını daxil edin", owner: "Administrator", status: "Gözləyir" },
      { id: "ONB-2", title: "İlk anbarı yaradın", owner: "Administrator", status: "Gözləyir" },
      { id: "ONB-3", title: "Məhsul kataloqunu və ilkin mədaxili yaradın", owner: "Administrator", status: "Gözləyir" },
      { id: "ONB-4", title: "İstifadəçi və rolları təyin edin", owner: "Administrator", status: "Gözləyir" },
      { id: "ONB-5", title: "Kassa və bank açılış balanslarını daxil edin", owner: "Maliyyə", status: "Gözləyir" },
      { id: "ONB-6", title: "Əməkdaş məlumatlarını daxil edin", owner: "HR", status: "Gözləyir" },
    ],
  },
  invoiceSettings: {
    prefix: "EQ",
    vatRate: 18,
    paymentTermsDays: 7,
    eTaxMode: "E-qaimə inteqrasiya rejimi",
    defaultCurrency: "AZN",
  },
  settings: {
    company: "",
    voen: "",
    phone: "",
    email: "",
    address: "",
    toggles: {
      push: true,
      sms: true,
      email: true,
      creditWarnings: true,
      lowStock: true,
    },
    sessionUserId: "USR-ADMIN",
    users: [
      {
        id: "USR-ADMIN",
        name: "Administrator",
        email: "Agarehim777@gmail.com",
        role: "Super Admin",
        status: "Aktiv",
      },
    ],
  },
};

export const reportTemplates = [
  { title: "Aylıq satış hesabatı", desc: "Satış, məhsul və satıcı üzrə icmal", cadence: "Aylıq" },
  { title: "Maliyyə mənfəət/zərər", desc: "Gəlir, xərc və net nəticə", cadence: "Aylıq" },
  { title: "Anbar hərəkəti", desc: "Mədaxil, rezerv, təhvil və qalığa baxış", cadence: "Həftəlik" },
  { title: "Kredit portfeli", desc: "Aktiv, gecikən və bağlanan kreditlər", cadence: "Gündəlik" },
];

export const goals = [];

export const contractTemplates = [
  { title: "Satış müqaviləsi", desc: "Müştəri, məhsul və qiymət avtomatik doldurulur" },
  { title: "Kredit satış müqaviləsi", desc: "Aylıq ödəniş cədvəli əlavə olunur" },
  { title: "Topdan satış müqaviləsi", desc: "Çoxsaylı məhsul və endirim sxemi" },
  { title: "Xidmət müqaviləsi", desc: "Servis şərtləri və zəmanət" },
];
