// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Use to verify connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool2({
  name: "whoami",
  title: "Whoami",
  description: "Return the signed-in user's id and email as verified from the OAuth token.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = { userId: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/orders-list.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.7";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
  }
  return null;
}

// src/lib/mcp/tools/orders-list.ts
var orders_list_default = defineTool3({
  name: "orders_list",
  title: "List orders",
  description: "List the signed-in user's orders (most recent first).",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(50).describe("Max rows to return."),
    status: z2.string().optional().describe("Optional status filter (e.g. pending, paid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let q = supabaseForUser(ctx).from("orders").select("id, customer_name, total_amount, status, notes, created_at, updated_at").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/orders-get.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var orders_get_default = defineTool4({
  name: "orders_get",
  title: "Get order",
  description: "Get a single order owned by the signed-in user, by id.",
  inputSchema: { id: z3.string().uuid().describe("Order id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("orders").select("id, customer_name, total_amount, status, notes, created_at, updated_at").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/projects-list.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
var projects_list_default = defineTool5({
  name: "projects_list",
  title: "List projects",
  description: "List projects within the signed-in user's active tenant (most recent first). Data is scoped to the current company by RLS.",
  inputSchema: {
    limit: z4.number().int().min(1).max(200).default(50).describe("Max rows to return."),
    status: z4.string().optional().describe("Optional status filter (e.g. active, done).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let q = supabaseForUser(ctx).from("projects").select("id, name, description, status, budget, start_date, end_date, created_at, updated_at").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/projects-get.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
var projects_get_default = defineTool6({
  name: "projects_get",
  title: "Get project",
  description: "Get a single project owned by the signed-in user, by id.",
  inputSchema: { id: z5.string().uuid().describe("Project id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("projects").select("id, name, description, status, budget, start_date, end_date, created_at, updated_at").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rojwxgndtunssjdwngrh";
var mcp_default = defineMcp({
  name: "erpaz-mcp",
  title: "ERPAZ Operations MCP",
  version: "0.2.0",
  instructions: "Tools for the ERPAZ operations suite. Use `echo` to verify connectivity, `whoami` for the signed-in user, `orders_list`/`orders_get` for orders, and `projects_list`/`projects_get` for projects. All data is scoped to the OAuth user via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, whoami_default, orders_list_default, orders_get_default, projects_list_default, projects_get_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
